# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DepenencyInjection' do
	source 'https://github.com/CocoaPods/Specs.git'
	platform :ios, '8.0'
	use_frameworks!

	pod 'Swinject', '2.0.0'
end
